AS gstex.asm
AS getcpu.asm
AS chgcpu.asm
AS di.asm
AS ei.asm
AS rdpsg.asm
AS sound.asm
AS kilbuf.asm
AS snsmat.asm
AS chgsnd.asm
AS gtpdl.asm
AS gtpad.asm
AS gttrig.asm
AS gtstck.asm
AS dspfnk.asm
AS erafnk.asm
AS inifnk.asm
AS locate.asm
AS cls.asm
AS beep.asm
AS breakx.asm
AS inlin.asm
AS pinlin.asm
AS lptstt.asm
AS lptout.asm
AS chget.asm
AS chput.asm
AS chsns.asm
AS gicini.asm
AS screen.asm
AS ENASCR.asm
AS DISSCR.asm

OL a mlib.irl gstex getcpu chgcpu di ei rdpsg sound kilbuf 
OL a mlib.irl snsmat chgsnd gtpdl gtpad gttrig gtstck dspfnk erafnk 
OL a mlib.irl inifnk locate cls beep breakx inlin pinlin lptstt 
OL a mlib.irl lptout chget chput chsns gicini screen ENASCR DISSCR 
