as putspr.asm
as colspr.asm
as calatr.asm
as calpat.asm
as sprite.asm
as vdpcom.ASM
as rdvsts.ASM
as rdvdp.ASM
as wrtvdp.ASM
as vpoke.ASM
as vpeek.ASM
as setrd.ASM
as setwrt.ASM
as interlac.ASM
as iniplt.ASM
as setplt.ASM
as inispr.ASM
as glocate.ASM
as grpprt.ASM
as setpg.ASM
as color.ASM
as totext.ASM
as invdp.ASM
as outvdp.ASM
as fsetwt.ASM
as fsetrd.ASM
as ginit.ASM

OL a mlib.irl putspr colspr calatr calpat sprite
OL a mlib.irl vdpcom rdvsts rdvdp wrtvdp vpoke vpeek setrd setwrt 
OL a mlib.irl interlac iniplt setplt inispr glocate grpprt setpg color 
OL a mlib.irl totext invdp outvdp fsetwt fsetrd ginit 
